name: farm_rice_flutter_web
description: A new Flutter project.
authors: 8voComputacion

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.11.0 <3.0.0'
  #flutter: ">=2.0.1 <3.3.10"

dependencies:
  latlong2:
  intl:
  flutter_map:
  syncfusion_flutter_charts:
  http:
  shared_preferences:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
